### ISSUE TITLE
Tensorial product not displaying

### ISSUE THREAD

**Issue by roveroniandrea** [MicrosoftDocs/quantum-docs-pr.it-IT#3]
[Immetti qui i commenti]

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: feb830cc-7d9b-c13e-4652-115352ea1e29
* Version Independent ID: f9484b57-1dc8-06a9-ac6d-cdc7c4769981
* Content: [Algebra lineare per il calcolo quantistico - Microsoft Quantum](https://docs.microsoft.com/it-it/quantum/overview/algebra-for-quantum-computing)
* Content Source: [articles/overview/algebra-for-quantum-computing.md](https://github.com/MicrosoftDocs/quantum-docs-pr.it-it/blob/live/articles/overview/algebra-for-quantum-computing.md)
* Product: **quantum**
* GitHub Login: @Bradben
* Microsoft Alias: **bradben**

**Comment by srvbpigh** [comment]
Hello, @roveroniandrea
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @roveroniandrea 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - XXX.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
